server {
  listen 80 ssl;
  ssl_certificate /run/identity-tls/tls.crt;
  ssl_certificate_key /run/identity-tls/tls.key;
  ssl_protocols TLSv1.2 TLSv1.3;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  sub_filter_types text/html;
  sub_filter_once off;
  sub_filter '"/assets/' '"$http_x_identity_platform_application_prefix/assets/';

  location = /assets/deployment-config.js {
    add_header Cache-Control "no-store, no-cache, must-revalidate" always;
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
