server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  sub_filter_types text/html;
  sub_filter_once off;
  sub_filter '"/assets/' '"$http_x_identity_platform_application_prefix/assets/';

  location / {
    try_files $uri $uri/ /index.html;
  }
}
